package com.hcsc.bridge.audit;

public enum AuditEventType {
    MESSAGE_RECEIVED,
    MESSAGE_PARSED,
    ENRICHMENT_COMPLETED,
    ENRICHMENT_FAILED,
    HDFS_WRITE_COMPLETED,
    HDFS_WRITE_FAILED,
    HDFS_WRITE_SKIPPED,
    KAFKA_PUBLISH_COMPLETED,
    KAFKA_PUBLISH_FAILED,
    PROCESSING_COMPLETED,
    PROCESSING_FAILED,
    DUPLICATE_DETECTED,
    RECOVERY_STARTED,
    RECOVERY_COMPLETED,
    RECOVERY_FAILED,
    RECONCILIATION_STARTED,
    RECONCILIATION_COMPLETED,
    RECONCILIATION_MISMATCH
}
